### ISSUE TITLE
Difference between IDE and Maven

### ISSUE THREAD

**Issue by kavukcutolga** [Cosium/maven-git-code-format#18]
Hi,

I am wondering why google-style in IDE is conflicting with maven plugin. For example

```
package my.package;

import another.package.helper.LogHelper;

public class AClass {

  /**
   * Log instance.
   */
  private static final LogHelper LOGGER = new LogHelper(AClass.class);
}

```

This class is not valid for maven because of comment format. But both in Intellij and Eclipse this comment block is not formatted back. Bun if I run validate

`AClass.java is not correctly formatted ! -> [Help 1] 
`
Then I format the code here is the valid format for maven plugin

```
package my.package;

import another.package.helper.LogHelper;

public class AClass {

  /** Log instance. */
  private static final LogHelper LOGGER = new LogHelper(AClass.class);
}

```

See the difference in comment block. But both formats are valid for IDEs ?

Any ideas ? This is kinda annoying since you think you formatted on IDE with google format but it is not validated by plugin ?

**Comment by reda-alaoui** [comment]
Hi,

I would say that your IDE is wrongly configured.
I use IntelliJ with google-java-format and one line comments are always inlined by my IDE.

**Comment by reda-alaoui** [comment]
![Screenshot from 2019-06-19 15-01-02](https://user-images.githubusercontent.com/2890843/59767683-1ddf2a80-92a3-11e9-9baa-e9a8ae7209a9.png)

**Comment by kavukcutolga** [comment]
I see you are using the  google-java-format plugin for Intellij, what I mean is using google style for editor. I will check with plugin as well so can we say that maven plugin is only compatible with Intellij   google-java-format plugin 

![image](https://user-images.githubusercontent.com/10419593/59768048-ecb32a00-92a3-11e9-9a2d-e2c167c8c77a.png)

**Comment by kavukcutolga** [comment]
With plugin it works as expected but still in Eclipse one line javadocs are not inlined with google eclipse format
https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

**Comment by reda-alaoui** [comment]
The Google Java style guide is flexible about the inline.
From https://google.github.io/styleguide/javaguide.html#s7.1-javadoc-formatting

> The single-line form may be substituted when the entirety of the Javadoc block (including comment markers) can fit on a single line.

Anyway this project use google-java-format. If you find a way to disable javadoc inlining in google-java-format, I would be happy to merge your PR.
