### ISSUE TITLE
incompatible with Java 7

### ISSUE THREAD

**Issue by jfairley** [Cosium/maven-git-code-format#2]
I love the idea, but my app is incompatible with JDK8, so I can't use this plugin. 🙁

**Comment by jfairley** [comment]
Well, it seems like `com.google.googlejavaformat:google-java-format` requires Java8, so I guess there's nothing to be done here. Closing.

**Comment by reda-alaoui** [comment]
Hello @jfairley ,
Sorry.
I guess it is time to move to Java 8.
Or do your users requires Java 7 compat?

**Comment by jfairley** [comment]
A third-party dependency, actually. We're working on replacing it, but unfortunately it's a mountain of tech debt...

**Comment by reda-alaoui** [comment]
Beside that, IMO you can have Maven running Java 8 to build a Java 7 project.

**Comment by jfairley** [comment]
My runtime dependency affects surefire tests in using Java 8.

>
