### ISSUE TITLE
skip running maven goals when there is no changed java files

### ISSUE THREAD

**Issue by tracyhenry** [Cosium/maven-git-code-format#20]
Right now even when I commit a README, the maven goal will be triggered, which can be slow and confusing.

**Comment by reda-alaoui** [comment]
In the future, this plugin may format non java files.
Because of this, leaving the plugin itself decides which file types it supports is more maintainable than pouring intelligence in the pre-commit hook shell.

Because of this and the fact that, in my experience, the drawback on the "slowness" and "confusion" is negligible, the current behaviour will remain the same.

**Comment by pelmato** [comment]
Actually it is a no-go for my team as the pre-commit hook takes more or less 1 minute even if there is only 1 file to commit.
If I add a new goal which applies formatting only on staged files, will you accept it?

**Comment by reda-alaoui** [comment]
> Actually it is a no-go for my team as the pre-commit hook takes more or less 1 minute even if there is only 1 file to commit.

I never experienced such delay for 1 file. You are the first telling me this. That's a bug either related to the plugin or to something else.

> If I add a new goal which applies formatting only on staged files, will you accept it?

This is what the pre-commit hook already does.

**Comment by reda-alaoui** [comment]
In any case, this discussion should happend in a dedicated issue, it is not related to the current issue.

**Comment by pelmato** [comment]
OK. Just to let you know: the cause of my problem was that my project contains a lot of nested maven modules and the execution was called on every module. I was able to solve it using the **includedModules** configuration.

```xml
<plugin>
  <groupId>com.cosium.code</groupId>
  <artifactId>maven-git-code-format</artifactId>
  <version>1.37</version>
  <configuration>
    <includedModules>myRootModule</includedModules>
  </configuration>
  <executions>
  ...
</plugin>
```

I think it would be worth adding documentation for the includedModules and excludedModules options.

Thanks
