### ISSUE TITLE
Cannot lock .git/index

### ISSUE THREAD

**Issue by benmccann** [Cosium/maven-git-code-format#22]
I'm interesting in trying out this project, but having some trouble getting started.

* If I have a multi-module project, do I need to install anything in the sub-projects?
* Do I need to run `mvn initialize` or is that a stage that happens automatically when I run `mvn compile` or `mvn test`?
* I'm not noticing anything happening. Are there any common errors I might be making?

Thanks!

**Comment by reda-alaoui** [comment]
Hi Ben,

* As stated in the README, you only need to put the plugin in your root project `pom.xml`. By default all submodules will be handled.
* `initialize` is the first phase of the Maven lifecycle. Any goal that you perform (e.g. compile or test) will automatically trigger `initialize` and thus trigger the git pre-commit hook installation.
* You have to be more accurate. If after setting up the plugin in your pom, you just executed a maven goal, the only expected output is a pre-commit hook installed in your `.git` directory. To trigger the automatic formatting, you have to perform a commit of a modified java file.

If you are still having trouble, feel free to post your maven configuration (at least the plugin part) and describe exactly what is happening.

**Comment by benmccann** [comment]
It's installed the pre-commit hook. However, when I try to do a commit I get the error message:

> [ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.28:on-pre-commit (default-cli) on project tablesaw-parent: Cannot lock .git/index. Ensure that no other process has an open file handle on the lock file .git/index.lock, then you may delete the lock file and retry. -> [Help 1]

This is strange because there is no file `.git/index.lock` that exists

**Comment by reda-alaoui** [comment]
Please show me the maven configuration and the .git directory content with its files content.

Réda Housni Alaoui

**Comment by benmccann** [comment]
Maven configuration:
```
    <build>
        <plugins>
            <plugin>
                <groupId>com.cosium.code</groupId>
                <artifactId>maven-git-code-format</artifactId>
                <version>1.28</version>
                <executions>
                    <!-- On commit, format the modified java files -->
                    <execution>
                        <id>install-formatter-hook</id>
                        <goals>
                            <goal>install-hooks</goal>
                        </goals>
                    </execution>
                    <!-- On Maven verify phase, fail if any file 
                    (including unmodified) is badly formatted -->
                    <execution>
                        <id>validate-code-format</id>
                        <goals>
                            <goal>validate-code-format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

`.git` directory:
```
$ ls .git
branches  COMMIT_EDITMSG  config  description  FETCH_HEAD  HEAD  hooks  index  info  logs  objects  ORIG_HEAD  packed-refs  refs
```

**Comment by reda-alaoui** [comment]
I meant the content of each file inside `.git/hooks`, my mistake.
Or even better, could you provide a git repository allowing to reproduce the issue?
And what is your OS and your git version?

**Comment by reda-alaoui** [comment]
Also do you commit using the CLI or otherwise?

**Comment by benmccann** [comment]
Using the CLI

**Comment by benmccann** [comment]
Here's a git repo: https://github.com/jtablesaw/tablesaw/tree/cosium

```
$ git --version
git version 2.7.4
$ cat /etc/upstream-release/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```

**Comment by reda-alaoui** [comment]
I cloned your repo, I cannot reproduce your issue.
I use git version 2.17.1 on Ubuntu 18.04.3 LTS.

Can you upgrade your git version?
If it is not enough, can you try to clone a fresh copy of your repository to check if that solves the issue?

**Comment by benmccann** [comment]
Unfortunately I'm not sure if I can easily upgrade my git version. I tried checking out the repo again, but that didn't work.

Here's the stacktrace:
```
[ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.28:on-pre-commit (default-cli) on project tablesaw-parent: Cannot lock /home/bmccann/src/tablesaw/.git/index. Ensure that no other process has an open file handle on the lock file /home/bmccann/src/tablesaw/.git/index.lock, then you may delete the lock file and retry. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.cosium.code:maven-git-code-format:1.28:on-pre-commit (default-cli) on project tablesaw-parent: Cannot lock /home/bmccann/src/tablesaw/.git/index. Ensure that no other process has an open file handle on the lock file /home/bmccann/src/tablesaw/.git/index.lock, then you may delete the lock file and retry.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot lock /home/bmccann/src/tablesaw/.git/index. Ensure that no other process has an open file handle on the lock file /home/bmccann/src/tablesaw/.git/index.lock, then you may delete the lock file and retry.
	at com.cosium.code.format.OnPreCommitMojo.doExecute(OnPreCommitMojo.java:24)
	at com.cosium.code.format.AbstractModulMavenGitCodeFormatMojo.execute(AbstractModulMavenGitCodeFormatMojo.java:55)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /home/bmccann/src/tablesaw/.git/index. Ensure that no other process has an open file handle on the lock file /home/bmccann/src/tablesaw/.git/index.lock, then you may delete the lock file and retry.
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:251)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:328)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:294)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1238)
	at com.cosium.code.format.git.GitStagedFiles.format(GitStagedFiles.java:54)
	at com.cosium.code.format.OnPreCommitMojo.onPreCommit(OnPreCommitMojo.java:30)
	at com.cosium.code.format.OnPreCommitMojo.doExecute(OnPreCommitMojo.java:21)
	... 23 more
```

**Comment by benmccann** [comment]
It looks like that code is doing `new File("/home/bmccann/src/tablesaw/.git/index.lock").createNewFile()`. When I write my own Java program to do it then it works. I'm not quite sure what it might be doing differently

**Comment by benmccann** [comment]
Unfortunately, upgrading jgit did not fix this. I'm still getting the issue with the latest release

**Comment by reda-alaoui** [comment]
> It looks like that code is doing `new File("/home/bmccann/src/tablesaw/.git/index.lock").createNewFile()`. When I write my own Java program to do it then it works. I'm not quite sure what it might be doing differently

Your java code is not executed during a commit. Maybe your version of Git or something locks the index itself just before triggering the pre-commit hook.
You would have to verify that by putting a breakpoint (inside the maven plugin) just before the execption to take the time to check if the lock file exists before trying to add it.

**Comment by reda-alaoui** [comment]
I just tried with git version 2.7.4 on Ubuntu 16.04 (using docker image ubuntu:16.04)
I still don't reproduce :/

**Comment by reda-alaoui** [comment]
Could it be a user permission issue?

**Comment by benmccann** [comment]
I wrote a Java program that has the few lines below that works. Still can't figure out what's different between it and the Maven plugin
```
    Repository repository = new FileRepositoryBuilder().findGitDir(new File("/home/bmccann/src/tablesaw")).build();
    Git git = new Git(repository);
    DirCache dirCache = repository.lockDirCache();
```

I don't think there should be any permission issues. I'm running everything as my own user

**Comment by benmccann** [comment]
`mvn git-code-format:format-code -DglobPattern=**/*` works for me.

If I run `mvn -f pom.xml git-code-format:on-pre-commit` then it seems to run on every sub-project, but it doesn't actually format any files. I wonder if it's running multiple times (once per subproject) and that's what's causing the issue with the lock file
```
[INFO] Reactor Summary:
[INFO] 
[INFO] Tablesaw ........................................... SUCCESS [  2.166 s]
[INFO] tablesaw-core ...................................... SUCCESS [  0.124 s]
[INFO] tablesaw-beakerx ................................... SUCCESS [  0.096 s]
[INFO] tablesaw-excel ..................................... SUCCESS [  0.069 s]
[INFO] tablesaw-html ...................................... SUCCESS [  0.067 s]
[INFO] tablesaw-json ...................................... SUCCESS [  0.068 s]
[INFO] tablesaw-jsplot .................................... SUCCESS [  0.087 s]
[INFO] tablesaw-aggregate ................................. SUCCESS [  0.140 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.358 s
[INFO] Finished at: 2019-08-19T14:27:11-07:00
[INFO] Final Memory: 29M/317M
[INFO] ------------------------------------------------------------------------
```

**Comment by benmccann** [comment]
I filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=550232 asking for additional debug logging

**Comment by reda-alaoui** [comment]
> `mvn git-code-format:format-code -DglobPattern=**/*` works for me.
> 
> If I run `mvn -f pom.xml git-code-format:on-pre-commit` then it seems to run on every sub-project, but it doesn't actually format any files
> 
> ```
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] Tablesaw ........................................... SUCCESS [  2.166 s]
> [INFO] tablesaw-core ...................................... SUCCESS [  0.124 s]
> [INFO] tablesaw-beakerx ................................... SUCCESS [  0.096 s]
> [INFO] tablesaw-excel ..................................... SUCCESS [  0.069 s]
> [INFO] tablesaw-html ...................................... SUCCESS [  0.067 s]
> [INFO] tablesaw-json ...................................... SUCCESS [  0.068 s]
> [INFO] tablesaw-jsplot .................................... SUCCESS [  0.087 s]
> [INFO] tablesaw-aggregate ................................. SUCCESS [  0.140 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.358 s
> [INFO] Finished at: 2019-08-19T14:27:11-07:00
> [INFO] Final Memory: 29M/317M
> [INFO] ------------------------------------------------------------------------
> ```

You must have at least one modified git staged java file for the `on-pre-commit` to format it. Did you?

**Comment by zziga** [comment]
Getting the same issue with 1.28 and with 1.27. Version 1.26 works fine.

> [ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.27:on-pre-commit (default-cli) on project foo: Cannot lock /data/bamboo/home/xml-data/build-dir/1000/X-Y-JOB1/.git/index. Ensure that no other process has an open file handle on the lock file /data/bamboo/home/xml-data/build-dir/1000/X-Y-JOB1/.git/index.lock, then you may delete the lock file and retry.

I can reproduce the issue on CI (jdk 8, apache-maven-3.5.4, maven-release-plugin-2.5.3).
In clean phase, `pre-commit`, `post-commit`, and `*maven-git-code-format*.sh` get deleted from `.git/`. Then, goal 'install-hooks' adds hook back (a workaround to make sure old hooks get removed).

The *Cannot lock .git/index* I get during Maven release.  `mvn release:prepare`, after completing _Executing goals 'clean verify'_ tries to commit pom.xml with incremented version. and fails.

`mvn clean package` on the same CI environment is not affected, I probably don't have the case to trigger pre-commit hook during 'normal' build. Locally, on developer machines, pre-commit hooks works fine - tested with 1.28.

**Comment by mprisco-mdsol** [comment]
I confirmed that I get the same problem and that the latest version of the plugin that works for me is 1.26. My git client version is 2.23.0, Maven version is 3.6.2, JDK version is 1.8.0_212 and OS is Mac Mojave version 10.14.6 (with sudoer user). I get the issue in both cases where the git commit is invoked via CLI or Sourcetree tool. I applied the same Maven configuration as shown on the GitHub repo.

**Comment by reda-alaoui** [comment]
@benmccann , @zziga , @mprisco-mdsol , nobody at my company has your issue. Our CI (jenkins) works perfectly fine with the plugin. I can't reproduce the bug. 
Since you are able to reproduce it, please debug the plugin yourself or contact me (email on my github profile) to schedule a remote debug session.

**Comment by djcooke** [comment]
I was having this issue as well when adding files and commiting in one command:

```
git commit -a -m "commit message"
```

It works when I break it into separate commands to add and commit:

```
git add -A
git commit -m "commit message"
```

**Comment by reda-alaoui** [comment]
Maybe it is a timing issue.
The new version 1.33 retries locking up to 10 times once per second.
Please tell me if that fixed the issue.

**Comment by reda-alaoui** [comment]
Reproduced on Windows thanks to @djcooke instructions.
Retrying does not fix it.

**Comment by reda-alaoui** [comment]
According to my research and https://public-inbox.org/git/CAE0unxxzBpTr1afmKfQm_nJYo5oFOftih+vE+wQbFW809rXdaA@mail.gmail.com/T/#t, pre-commit hook were only expected to fail or let the commit pass.
Using `git commit -a` [locks](https://github.com/git/git/blob/master/builtin/commit.c#L419) the index before hooks execution.

**So for now, the solution is to use `git add . && git commit` instead of `git commit -a`.**

This instruction and current issue are going to be referred by the error message until I find a better solution.

**Comment by reda-alaoui** [comment]
https://github.com/Cosium/maven-git-code-format/commit/88197040a9de7716317723a626c201349dfbd533 fixes it totally.

Starting with 1.36, the plugin is now `git commit -a` compliant :tada:
