### ISSUE TITLE
Removing unused imports is not working

### ISSUE THREAD

**Issue by gtskaushik** [Cosium/maven-git-code-format#24]
**Following is the import statement**
_import com.jcraft.jsch.*;_

When I tried the _**mvn git-code-format:format-code -DglobPattern=**/***_, the import statement is not getting removed. But when the import statement does not have wildcards, it is working perfectly fine.

**Comment by reda-alaoui** [comment]
Hi,

Does it work with google-java-format CLI?

**Comment by gtskaushik** [comment]
I didn't check it. I'll try it out and update here

**Comment by reda-alaoui** [comment]
Also your glob pattern is incorrect. It should be **/* instead of ***.

**Comment by reda-alaoui** [comment]
Ok. Closing until you make your test.
