### ISSUE TITLE
Plugin is altering source content having special encoding chars

### ISSUE THREAD

**Issue by fcamblor** [Cosium/maven-git-code-format#25]
Hi, and before anything, thanks for the nice plugin, it's very useful !

I'm facing an issue with it though : if I introduce some special chars (like `é` which is pretty common in french 🇫🇷), the plugin is altering the commited content.

To reproduce, I prepared a very simple git repository here : https://github.com/fcamblor/maven-git-code-format-encoding-issue

The repository consists of a single Hello java file with nothing special inside it.

Now, if I apply following patch on it :
```
--- c/src/main/java/fr/camblor/hello/Hello.java
+++ i/src/main/java/fr/camblor/hello/Hello.java
@@ -2,6 +2,7 @@ package fr.camblor.hello;

  public class Hello {
    public static void main(String... args) {
 +    // éééé
      System.out.println("Hello world !");
    }
  }
```
<img width="601" alt="BeforeCommit" src="https://user-images.githubusercontent.com/603815/64017270-7b0c1d80-cb29-11e9-96b9-4e864bb76f0a.png">

and I commit this change, then I have weird thing happening :

1.  Commited content is containing `// <E9><E9><E9><E9>` instead of `// éééé` : it can be viewable [on the `generated-amended-code` branch, on raw file](https://raw.githubusercontent.com/fcamblor/maven-git-code-format-encoding-issue/generated-amended-code/src/main/java/fr/camblor/hello/Hello.java) (note that on the github file browser, [those special chars are displayed nicely](https://github.com/fcamblor/maven-git-code-format-encoding-issue/blob/generated-amended-code/src/main/java/fr/camblor/hello/Hello.java), so don't be tricked by this :-))
2. My initial content is available in local repository unstaged changes

<img width="605" alt="AfterCommit" src="https://user-images.githubusercontent.com/603815/64017300-90814780-cb29-11e9-9fa1-5f465f37f3ff.png">

Note that in `pom.xml`, I defined `project.build.sourceEncoding` to `UTF-8`
Not sure if this encoding is taken into consideration while altering files.

As a workaround, when I have to commit such changes, I have to :
1.  temporarily comment line in `.git/hooks/pre-commit`
2.  amend commit : `git add -u && git commit --amend`
3.  remove temporary comment in `.git/hooks/pre-commit`
4.  remove `validate-code-format` execution in my pom, as `validate-code-format` considers my "fixed" file content (with `ééé`) as a "non formatted" file

**Comment by fcamblor** [comment]
Also, note that when I directly use [`google-java-format`](https://github.com/google/google-java-format) jar file on my Hello world containing `ééé`, file is not altered at any moment.

That's why I suspect the plugin to melt with file encoding somewhere.

**Comment by botcoder** [comment]
I had the same issue. It's configured with aosp and fixImportsOnly, but for some reason it also changed the files to match the platform charset.

**Comment by fcamblor** [comment]
@reda-alaoui Just tested with `1.31-SNAPSHOT` and it's working now

Thanks for the quick fix :-)

**Comment by reda-alaoui** [comment]
:champagne: 
Thanks for the feedback

**Comment by reda-alaoui** [comment]
FYI, 1.30 contains the fix.
