### ISSUE TITLE
Manual formatting/validating misses files

### ISSUE THREAD

**Issue by djcooke** [Cosium/maven-git-code-format#27]
Hello,

My build was failing due to incorrectly formatted code in files under `.../src/it/java/`. When I manually ran the formatter (`mvn git-code-format:format-code -DglobPattern=**/*`), it did not format these files. When I manually ran the validator (`mvn git-code-format:validate-code-format -DglobPattern=**/*`), it did not check these files, and completed successfully.

I was able to get around the issue by changing each of the affected files and then committing them. The formatter run by pre-commit hook did format the affected files.

My plugin config from `pom.xml`:

```
            <plugin>
              <groupId>com.cosium.code</groupId>
              <artifactId>maven-git-code-format</artifactId>
              <version>1.32</version>
              <executions>
                <execution>
                  <id>install-formatter-hook</id>
                  <goals>
                    <goal>install-hooks</goal>
                  </goals>
                </execution>
                <execution>
                  <id>validate-code-format</id>
                  <goals>
                    <goal>validate-code-format</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
```

**Comment by reda-alaoui** [comment]
Manual formatter and validator browse directories provided by `MavenProject.getCompileSourceRoots()` and `MavenProject.getTestCompileSourceRoots`.
MavenProject is part of maven core.

You have to make maven consider your `.../src/it/java/` as a test source root.

Found on https://www.testwithspring.com/lesson/running-integration-tests-with-maven/ :
```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <version>1.12</version>
    <executions>
        <execution>
            <id>add-integration-test-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
                <goal>add-test-source</goal>
            </goals>
            <configuration>
                <sources>
                    <source>src/integration-test/java</source>
                </sources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by djcooke** [comment]
Hi, thanks for the response.

I did have `build-helper-maven-plugin` configured that way, though I was using an older version of it (1.9.1). I tried updating to 1.12, and also to the newest version (3.0.0), but got the same results with all versions.

When I run `mvn clean install`, build fails with this error:

> [ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.32:validate-code-format (validate-code-format) on project pinery-client: .../pinery/pinery-client/src/it/java/ca/on/oicr/pinery/client/AttributeNameClientIT.java is not correctly formatted ! -> [Help 1]

When I run `mvn git-code-format:validate-code-format -DglobPattern=**/*`, it is successful, and none of the files in `src/it/java/` are checked.

Project: https://github.com/oicr-gsi/pinery

**Comment by reda-alaoui** [comment]
Ok.
Without doing any further investigation I would say that the issue comes from the fact that you execute the formatter/validator outside of any maven phase. Because of that, build-helper-maven-plugin is not executed before manual formatter/validator.

Please try to bind build-helper-maven-plugin to the initialize phase and try again.

Réda Housni Alaoui

**Comment by reda-alaoui** [comment]
I just performed tests on your project.
If you bind build-helper-maven-plugin to `initialize` phase, running `mvn initialize git-code-format:validate-code-format -DglobPattern=**/*` includes `it` test classes.

If you are looking for a more elegant solution, I suggest you bring the subject to the Maven team.

**Comment by djcooke** [comment]
Thanks for the info. I just tried leaving the `build-helper-maven-plugin` in the `generate-test-sources` phase and running with the below commands, which each worked and included the integration test sources as well.

```
mvn test git-code-format:validate-code-format -DglobPattern=**/*
```

or

```
mvn generate-test-sources git-code-format:validate-code-format -DglobPattern=**/*
```
