### ISSUE TITLE
[ERROR] Could not find maven executable.

### ISSUE THREAD

**Issue by micycle1** [Cosium/maven-git-code-format#28]
```
[INFO] --- maven-git-code-format:1.32:install-hooks (install-formatter-hook) @ Project_16x16 ---
[INFO] Installing git hooks
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.004 s
[INFO] Finished at: 2019-11-11T19:09:36Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.32:install-hooks (install-formatter-hook) on project Project_16x16: Could not find maven executable. C:\Users\Mike\Documents\Project-16x16\EMBEDDED\bin\mvn does not exist. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Attempting to use the plugin and getting this. I'm quite new to Maven so help appreciated (note that project builds fine with existing plugins).

**Comment by reda-alaoui** [comment]
Hi @micycle1 ,

Can you provide the content of `C:\Users\Mike\Documents\Project-16x16\EMBEDDED` ?

**Comment by micycle1** [comment]
@reda-alaoui Well, it doesn't exist --- But then, why is maven-git-code-format looking for this folder?

**Comment by reda-alaoui** [comment]
The plugin looks for the java property `maven.home`. This is needed to find the maven executable of your system. 

It is valued to `C:\Users\Mike\Documents\Project-16x16\EMBEDDED` in your context. Only you can know why.

**Comment by micycle1** [comment]
I'm using maven eclipse plugin, which uses an embedded Maven (C:\Users\%USER%\.m2\repository) -- as such, there aren't any maven system path variables.

Does _maven-git-code-format_ require an installed maven version? It doesn't seem to be picking up the maven executable from Eclipse.
