### ISSUE TITLE
Cannot compile unless code is first committed.

### ISSUE THREAD

**Issue by mcpierce** [Cosium/maven-git-code-format#29]
On our project, we just added the plugin and formatted our entire codebase (which worked great, BTW).

But when I try to compile our project I'm now getting the following error:
```
[ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.36:validate-code-format (validate-code-format) on project ktc-services: /Users/mcpierce/Repositories/know-the-costs/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java is not correctly formatted ! -> [Help 1]
```

Even though our entire codebase was formatted by the plugin. If I git commit the code, without changing it, the build runs fine.

I should also add that I'm using the google-java-format plugin for IntellJ to format code as I go, so the code being saved as pre-formatted correctly.

**Comment by reda-alaoui** [comment]
Hi @mcpierce ,

IntelliJ google-java-format plugin does not format the code exactly as the plain google-java-format project used by this plugin.

I think what happens is that, somehow, between the full manual git-code-format formatting and the moment you perform your maven build, IntelliJ reformat the code in its own way. This breaks the formatting from maven-git-code-format point of view.

To verify this theory:
- close IntelliJ
- trigger manual format from the terminal
- run the maven build from the terminal
A passing build will confirm that IntelliJ is causing the issue.

**Comment by mcpierce** [comment]
@reda-alaoui Merci pour ta réponse.

I'm not sure that IntelliJ is the culprit here. It doesn't automatically reformat the code. But to be sure, I shutdown IntelliJ. The current state of the code is the following:

```
mcpierce@MacPierceBookPro ~/Repositories/know-the-costs/ktc-app (dpierce/PRTR-214) $ git diff
diff --git a/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java b/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java
index d104200dd..b19739b49 100644
--- a/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java
+++ b/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java
@@ -14,14 +14,15 @@ import com.outpatientservicesllc.model.WorkQueueItemQueueStage;
 import com.outpatientservicesllc.persistence.entities.*;
 import com.outpatientservicesllc.persistence.entities.patient.Patient;
 import com.outpatientservicesllc.persistence.repository.WorkQueueRepository;
-import java.util.*;
-import javax.transaction.Transactional;
-import javax.transaction.Transactional.TxType;
 import lombok.extern.log4j.Log4j2;
 import org.apache.commons.lang3.StringUtils;
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;

+import javax.transaction.Transactional;
+import javax.transaction.Transactional.TxType;
+import java.util.*;
+
 @Service
 @Log4j2
 public class WorkQueueService {
``` 

So the only thing changed are a few imports. When I compile, I get:

```
[ERROR] Failed to execute goal com.cosium.code:maven-git-code-format:1.36:validate-code-format (validate-code-format) on project ktc-services: /Users/mcpierce/Repositories/know-the-costs/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java is not correctly formatted ! -> [Help 1]
```

I commit the code and change is:

```
diff --git a/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java b/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java
index 668b7d6a4..d104200dd 100644
--- a/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java
+++ b/ktc-services/src/main/java/com/outpatientservicesllc/persistence/service/WorkQueueService.java
@@ -16,6 +16,7 @@ import com.outpatientservicesllc.persistence.entities.patient.Patient;
 import com.outpatientservicesllc.persistence.repository.WorkQueueRepository;
 import java.util.*;
 import javax.transaction.Transactional;
+import javax.transaction.Transactional.TxType;
 import lombok.extern.log4j.Log4j2;
 import org.apache.commons.lang3.StringUtils;
 import org.springframework.beans.factory.annotation.Autowired;
@@ -32,22 +33,6 @@ public class WorkQueueService {
```

Lastly, what I have in my pom.xml is the following (probably should have included this in the ticket earlier):

```
      <plugin>
        <groupId>com.cosium.code</groupId>
        <artifactId>maven-git-code-format</artifactId>
        <version>1.36</version>
        <executions>
          <execution>
            <id>install-formatter-hook</id>
            <goals>
              <goal>install-hooks</goal>
            </goals>
          </execution>
          <execution>
            <id>validate-code-format</id>
            <goals>
              <goal>validate-code-format</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <googleJavaFormatOptions>
            <aosp>false</aosp>
            <skipSortingImports>false</skipSortingImports>
            <skipRemovingUnusedImports>false</skipRemovingUnusedImports>
          </googleJavaFormatOptions>
        </configuration>
      </plugin>
```

**Comment by mcpierce** [comment]
@reda-alaoui Commented out the validate and the build ran correctly. Disabling that won't affect the overall formatting on commit though, yeah?

**Comment by reda-alaoui** [comment]
I think I understand more clearly your issue.

I bet you are using `mvn install` to perform your build. `install` triggers the `verify` phase.

By default, `validate-code-format` is bound to maven `verify` phase. The purpose of `validate-code-format` is to make the CI fail the build if it receives badly formatted files. Badly formatted files could be committed because of a developer that commit without ever running maven (i.e. no installed hooks) or a 'malicious' developer that manually removes the hook. The CI is then the last defense against this.

Disabling `validate-code-format` will only remove this guard. The pre-commit formatting will keep working without any issue.

If you want to keep `validate-code-format` for the CI while being able to run `mvn install` locally despite badly formatted files, you have to move it into a maven profile that would be enabled by your CI only.

**Comment by mcpierce** [comment]
@reda-alaoui Okay, understood. We'll adjust our system to use a profile for CI that runs the check at build time. Thank you!

**Comment by mcpierce** [comment]
@reda-alaoui One more question: could your provide an example of using profiles to configure this plugin? Would I change teh valu e for the goal based on the profile? If so, what value should be used for non-CI builds (as I would like the validation then, but not during a local build)?
