### ISSUE TITLE
Turn off formatting output

### ISSUE THREAD

**Issue by mcpierce** [Cosium/maven-git-code-format#30]
Is there a way to turn off logging output for the formatting when it runs?

**Comment by reda-alaoui** [comment]
Do you want to turn off the whole maven output or just the plugin output?
During the pre-commit hook and/or the manual formatting?

There is currently no way. But I am open to suggestions.

**Comment by mcpierce** [comment]
I’d like to turn off the plugin’s output. We have a lot of files in our
project and Travis fails builds when the logging output is too long. And
given the plugs outputs a line for each file processed it has started
failing for that reason.
-- 
Sent from Gmail Mobile

**Comment by mcpierce** [comment]
So is that a no on this being an enhancement?

**Comment by reda-alaoui** [comment]
The enhancement is implemented.
Take a look at the related commit

**Comment by mcpierce** [comment]
@reda-alaoui Ah, sorry, I didn't realize it was closed with a commit. Thank you!

**Comment by reda-alaoui** [comment]
No worry :) 
It is available since my previous comment.
