### ISSUE TITLE
AOSP formatting not working in 1.4

### ISSUE THREAD

**Issue by icopp** [Cosium/maven-git-code-format#33]
With..

```
<plugin>
    <groupId>com.cosium.code</groupId>
    <artifactId>maven-git-code-format</artifactId>
    <version>1.4</version>
    <executions>
        <execution>
            <id>install-formatter-hook</id>
            <goals>
                <goal>install-hooks</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <googleJavaFormatOptions>
            <aosp>true</aosp>
        </googleJavaFormatOptions>
    </configuration>
</plugin>
```

...files are being formatted to 2 spaces rather than 4 on commit.

**Comment by icopp** [comment]
Actually, it just seems to be ignoring any entries in `configuration` altogether. For example, adding `fixImportsOnly` does nothing.

**Comment by reda-alaoui** [comment]
Take a look at https://github.com/Cosium/maven-git-code-format/issues/21#issuecomment-519954778

**Comment by icopp** [comment]
That doesn't help. I'm using the configuration setting from the README and it does work in 1.39, but it doesn't work in 1.4.

**Comment by icopp** [comment]
Nevermind, somehow I was interpreting `1.4` as `1.4.0` and `1.39` as `1.3.9`, but obviously that's wrong...
