### ISSUE TITLE
Property keys may conflict with other plugins

### ISSUE THREAD

**Issue by chonton** [Cosium/maven-git-code-format#37]
In order to prevent conflicting property keys across multiple plugins, most plugins implement a convention of prefixing their property names with the plugin name.  e.g. [jacoco maven plugin](https://www.eclemma.org/jacoco/trunk/doc/maven.html) uses "jacoco." as a property key prefix.  [Fabrica8io docker maven plugin](https://dmp.fabric8.io/) uses "docker." as a property key prefix.

What do you think of prefixing git-code-format property keys with "fmt."?

**Comment by reda-alaoui** [comment]
Let's use `gcf`
