### ISSUE TITLE
Rename plugin 

### ISSUE THREAD

**Issue by chonton** [Cosium/maven-git-code-format#38]
According to [Maven plugin guide](https://maven.apache.org/guides/plugin/guide-java-plugin-development.html), prefixing a plugin with "maven-" is discouraged and may be in violation of Apache trademarks.

Please rename the plugin.  Perhaps "pre-commit-maven-plugin"?

**Comment by reda-alaoui** [comment]
Oh I didn't know that.

In that case, let's rename it `git-code-format-maven-plugin`.
