### ISSUE TITLE
Plugin does not play nicely with partially staged files

### ISSUE THREAD

**Issue by rkraneis** [Cosium/maven-git-code-format#4]
I often commit quite late after playing around and partially stage files to have meaningful commits. The plugin does not play nicely with this workflow, as it stages the whole file (even if it wasn't a java file but e.g. pom.xml).

The plugin should only work on the staged state of a file and not regard a partially staged file as added.

**Comment by reda-alaoui** [comment]
Indeed.
Could you help with a Pull Request?
