### ISSUE TITLE
Plugin will fail when there is space in the file path

### ISSUE THREAD

**Issue by hongfei** [Cosium/maven-git-code-format#8]
Pre-commit run failed when there are files with spaces in the path (not java files).

For instance,
if one of the staged file path is: `some/directory/file name with path.txt`
will show error like
`fatal: pathspec 'some/directory/file' did not match any files`
 and then the commit is stopped.

**Comment by reda-alaoui** [comment]
Fixed by https://github.com/Cosium/maven-git-code-format/commit/a2d355bf06c6f4cd9ca3f78c385b7a6e32e26090
